### ISSUE TITLE
Minimal requirements for php version

### ISSUE THREAD

**Issue by garcher** [php-slang/php-slang#18]
Hello, in composer.json there is declaration for php version - "php": ">=7.0.1". Can it be decreased to 7.0.0 ? Is it a conscious decision? Because as for now I don't see anything that cannot be working at 7.0.0.

**Comment by wit3k** [comment]
Hi @garcher nice to hear you're interested with using a PhpSlang.
Initial decision was that we don't bother a lot about backward compatibility (especially PHP older than 7.0) but yes - PhpSlang does not use any 7.0.1 nor 7.1.0 features at the moment so I decreased the version number as you requested.
Feel free to use the latest version (currently dev-master, new version is going to be published when we'll have a 100% test coverage).
FYI we're going to stick with 7.0.0 till version 1.0 (cover all features from the roadmap). When we'll gather additional feedback and PhpSlang 1.1 will come - there is a chance that we'll use the newest PHP (in a day when 1.1 will be published).
