### ISSUE TITLE
API docs template

### ISSUE THREAD

**Issue by wit3k** [php-slang/php-slang#6]
Create a custom template for
http://www.mkdocs.org/

**Comment by piotrooo** [comment]
I recommend you to use a [sphinx-doc.org](http://www.sphinx-doc.org/en/stable/). It has more features than mkdocs :)

**Comment by wit3k** [comment]
Just checked sphinx-doc and yes - it looks much more promossing - big thanks @piotrooo

**Comment by wit3k** [comment]
@piotrooo sticked to daux at this moment - but sphinx is still an option
